/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const MatchFormat = IDL.Variant({
  'ipl' : IDL.Null,
  'odi' : IDL.Null,
  't20' : IDL.Null,
  'test' : IDL.Null,
});
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const NewsCategory = IDL.Variant({
  'ipl' : IDL.Null,
  'domestic' : IDL.Null,
  'international' : IDL.Null,
});
export const PlayerRole = IDL.Variant({
  'bowler' : IDL.Null,
  'allrounder' : IDL.Null,
  'wicketkeeper' : IDL.Null,
  'batsman' : IDL.Null,
});
export const BattingStats = IDL.Record({
  'centuries' : IDL.Nat,
  'runs' : IDL.Nat,
  'average' : IDL.Float64,
  'highScore' : IDL.Int,
  'matches' : IDL.Nat,
  'strikeRate' : IDL.Float64,
  'halfCenturies' : IDL.Nat,
});
export const BowlingStats = IDL.Record({
  'economy' : IDL.Float64,
  'average' : IDL.Float64,
  'wickets' : IDL.Nat,
  'bestFigures' : IDL.Text,
});
export const RecordCategory = IDL.Variant({
  'bowling' : IDL.Null,
  'team' : IDL.Null,
  'batting' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'result' : IDL.Text,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'venue' : IDL.Text,
  'date' : Time,
  'score1' : IDL.Text,
  'score2' : IDL.Text,
  'format' : MatchFormat,
});
export const NewsArticle = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'date' : Time,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : NewsCategory,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'bowlingStats' : BowlingStats,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'role' : PlayerRole,
  'battingStats' : BattingStats,
  'imageUrl' : IDL.Text,
});
export const Record = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'value' : IDL.Text,
  'year' : IDL.Nat,
  'category' : RecordCategory,
  'holder' : IDL.Text,
  'format' : MatchFormat,
});

export const idlService = IDL.Service({
  'createMatch' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        MatchFormat,
        MatchStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createNewsArticle' : IDL.Func(
      [IDL.Text, IDL.Text, NewsCategory, Time, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPlayer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        PlayerRole,
        BattingStats,
        BowlingStats,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createRecord' : IDL.Func(
      [RecordCategory, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, MatchFormat],
      [IDL.Nat],
      [],
    ),
  'deleteMatch' : IDL.Func([IDL.Nat], [], []),
  'deleteNewsArticle' : IDL.Func([IDL.Nat], [], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllRecords' : IDL.Func([], [IDL.Vec(Record)], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
  'getNewsArticle' : IDL.Func([IDL.Nat], [NewsArticle], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
  'getRecord' : IDL.Func([IDL.Nat], [Record], ['query']),
  'updateMatch' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        MatchFormat,
        MatchStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateNewsArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, NewsCategory, Time, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updatePlayer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        PlayerRole,
        BattingStats,
        BowlingStats,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateRecord' : IDL.Func(
      [
        IDL.Nat,
        RecordCategory,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        MatchFormat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const MatchFormat = IDL.Variant({
    'ipl' : IDL.Null,
    'odi' : IDL.Null,
    't20' : IDL.Null,
    'test' : IDL.Null,
  });
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const NewsCategory = IDL.Variant({
    'ipl' : IDL.Null,
    'domestic' : IDL.Null,
    'international' : IDL.Null,
  });
  const PlayerRole = IDL.Variant({
    'bowler' : IDL.Null,
    'allrounder' : IDL.Null,
    'wicketkeeper' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const BattingStats = IDL.Record({
    'centuries' : IDL.Nat,
    'runs' : IDL.Nat,
    'average' : IDL.Float64,
    'highScore' : IDL.Int,
    'matches' : IDL.Nat,
    'strikeRate' : IDL.Float64,
    'halfCenturies' : IDL.Nat,
  });
  const BowlingStats = IDL.Record({
    'economy' : IDL.Float64,
    'average' : IDL.Float64,
    'wickets' : IDL.Nat,
    'bestFigures' : IDL.Text,
  });
  const RecordCategory = IDL.Variant({
    'bowling' : IDL.Null,
    'team' : IDL.Null,
    'batting' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'result' : IDL.Text,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'venue' : IDL.Text,
    'date' : Time,
    'score1' : IDL.Text,
    'score2' : IDL.Text,
    'format' : MatchFormat,
  });
  const NewsArticle = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'date' : Time,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : NewsCategory,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'bowlingStats' : BowlingStats,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'role' : PlayerRole,
    'battingStats' : BattingStats,
    'imageUrl' : IDL.Text,
  });
  const Record = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'value' : IDL.Text,
    'year' : IDL.Nat,
    'category' : RecordCategory,
    'holder' : IDL.Text,
    'format' : MatchFormat,
  });
  
  return IDL.Service({
    'createMatch' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          MatchFormat,
          MatchStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createNewsArticle' : IDL.Func(
        [IDL.Text, IDL.Text, NewsCategory, Time, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPlayer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          PlayerRole,
          BattingStats,
          BowlingStats,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createRecord' : IDL.Func(
        [RecordCategory, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, MatchFormat],
        [IDL.Nat],
        [],
      ),
    'deleteMatch' : IDL.Func([IDL.Nat], [], []),
    'deleteNewsArticle' : IDL.Func([IDL.Nat], [], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllRecords' : IDL.Func([], [IDL.Vec(Record)], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
    'getNewsArticle' : IDL.Func([IDL.Nat], [NewsArticle], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
    'getRecord' : IDL.Func([IDL.Nat], [Record], ['query']),
    'updateMatch' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          MatchFormat,
          MatchStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateNewsArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, NewsCategory, Time, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updatePlayer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          PlayerRole,
          BattingStats,
          BowlingStats,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateRecord' : IDL.Func(
        [
          IDL.Nat,
          RecordCategory,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          MatchFormat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };