/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BattingStats {
  'centuries' : bigint,
  'runs' : bigint,
  'average' : number,
  'highScore' : bigint,
  'matches' : bigint,
  'strikeRate' : number,
  'halfCenturies' : bigint,
}
export interface BowlingStats {
  'economy' : number,
  'average' : number,
  'wickets' : bigint,
  'bestFigures' : string,
}
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'result' : string,
  'team1' : string,
  'team2' : string,
  'venue' : string,
  'date' : Time,
  'score1' : string,
  'score2' : string,
  'format' : MatchFormat,
}
export type MatchFormat = { 'ipl' : null } |
  { 'odi' : null } |
  { 't20' : null } |
  { 'test' : null };
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface NewsArticle {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'date' : Time,
  'summary' : string,
  'imageUrl' : string,
  'category' : NewsCategory,
}
export type NewsCategory = { 'ipl' : null } |
  { 'domestic' : null } |
  { 'international' : null };
export interface Player {
  'id' : bigint,
  'bio' : string,
  'bowlingStats' : BowlingStats,
  'country' : string,
  'name' : string,
  'role' : PlayerRole,
  'battingStats' : BattingStats,
  'imageUrl' : string,
}
export type PlayerRole = { 'bowler' : null } |
  { 'allrounder' : null } |
  { 'wicketkeeper' : null } |
  { 'batsman' : null };
export interface Record {
  'id' : bigint,
  'title' : string,
  'value' : string,
  'year' : bigint,
  'category' : RecordCategory,
  'holder' : string,
  'format' : MatchFormat,
}
export type RecordCategory = { 'bowling' : null } |
  { 'team' : null } |
  { 'batting' : null };
export type Time = bigint;
export interface _SERVICE {
  'createMatch' : ActorMethod<
    [
      string,
      string,
      string,
      Time,
      MatchFormat,
      MatchStatus,
      string,
      string,
      string,
    ],
    bigint
  >,
  'createNewsArticle' : ActorMethod<
    [string, string, NewsCategory, Time, string, boolean],
    bigint
  >,
  'createPlayer' : ActorMethod<
    [string, string, PlayerRole, BattingStats, BowlingStats, string, string],
    bigint
  >,
  'createRecord' : ActorMethod<
    [RecordCategory, string, string, string, bigint, MatchFormat],
    bigint
  >,
  'deleteMatch' : ActorMethod<[bigint], undefined>,
  'deleteNewsArticle' : ActorMethod<[bigint], undefined>,
  'deletePlayer' : ActorMethod<[bigint], undefined>,
  'deleteRecord' : ActorMethod<[bigint], undefined>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllNewsArticles' : ActorMethod<[], Array<NewsArticle>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllRecords' : ActorMethod<[], Array<Record>>,
  'getMatch' : ActorMethod<[bigint], Match>,
  'getNewsArticle' : ActorMethod<[bigint], NewsArticle>,
  'getPlayer' : ActorMethod<[bigint], Player>,
  'getRecord' : ActorMethod<[bigint], Record>,
  'updateMatch' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Time,
      MatchFormat,
      MatchStatus,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateNewsArticle' : ActorMethod<
    [bigint, string, string, NewsCategory, Time, string, boolean],
    undefined
  >,
  'updatePlayer' : ActorMethod<
    [
      bigint,
      string,
      string,
      PlayerRole,
      BattingStats,
      BowlingStats,
      string,
      string,
    ],
    undefined
  >,
  'updateRecord' : ActorMethod<
    [bigint, RecordCategory, string, string, string, bigint, MatchFormat],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];