/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    bio: string;
    bowlingStats: BowlingStats;
    country: string;
    name: string;
    role: PlayerRole;
    battingStats: BattingStats;
    imageUrl: string;
}
export type Time = bigint;
export interface Record_ {
    id: bigint;
    title: string;
    value: string;
    year: bigint;
    category: RecordCategory;
    holder: string;
    format: MatchFormat;
}
export interface NewsArticle {
    id: bigint;
    title: string;
    featured: boolean;
    date: Time;
    summary: string;
    imageUrl: string;
    category: NewsCategory;
}
export interface BowlingStats {
    economy: number;
    average: number;
    wickets: bigint;
    bestFigures: string;
}
export interface BattingStats {
    centuries: bigint;
    runs: bigint;
    average: number;
    highScore: bigint;
    matches: bigint;
    strikeRate: number;
    halfCenturies: bigint;
}
export interface Match {
    id: bigint;
    status: MatchStatus;
    result: string;
    team1: string;
    team2: string;
    venue: string;
    date: Time;
    score1: string;
    score2: string;
    format: MatchFormat;
}
export enum MatchFormat {
    ipl = "ipl",
    odi = "odi",
    t20 = "t20",
    test = "test"
}
export enum MatchStatus {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export enum NewsCategory {
    ipl = "ipl",
    domestic = "domestic",
    international = "international"
}
export enum PlayerRole {
    bowler = "bowler",
    allrounder = "allrounder",
    wicketkeeper = "wicketkeeper",
    batsman = "batsman"
}
export enum RecordCategory {
    bowling = "bowling",
    team = "team",
    batting = "batting"
}
export interface backendInterface {
    createMatch(team1: string, team2: string, venue: string, date: Time, format: MatchFormat, status: MatchStatus, result: string, score1: string, score2: string): Promise<bigint>;
    createNewsArticle(title: string, summary: string, category: NewsCategory, date: Time, imageUrl: string, featured: boolean): Promise<bigint>;
    createPlayer(name: string, country: string, role: PlayerRole, battingStats: BattingStats, bowlingStats: BowlingStats, imageUrl: string, bio: string): Promise<bigint>;
    createRecord(category: RecordCategory, title: string, holder: string, value: string, year: bigint, format: MatchFormat): Promise<bigint>;
    deleteMatch(id: bigint): Promise<void>;
    deleteNewsArticle(id: bigint): Promise<void>;
    deletePlayer(id: bigint): Promise<void>;
    deleteRecord(id: bigint): Promise<void>;
    getAllMatches(): Promise<Array<Match>>;
    getAllNewsArticles(): Promise<Array<NewsArticle>>;
    getAllPlayers(): Promise<Array<Player>>;
    getAllRecords(): Promise<Array<Record_>>;
    getMatch(id: bigint): Promise<Match>;
    getNewsArticle(id: bigint): Promise<NewsArticle>;
    getPlayer(id: bigint): Promise<Player>;
    getRecord(id: bigint): Promise<Record_>;
    updateMatch(id: bigint, team1: string, team2: string, venue: string, date: Time, format: MatchFormat, status: MatchStatus, result: string, score1: string, score2: string): Promise<void>;
    updateNewsArticle(id: bigint, title: string, summary: string, category: NewsCategory, date: Time, imageUrl: string, featured: boolean): Promise<void>;
    updatePlayer(id: bigint, name: string, country: string, role: PlayerRole, battingStats: BattingStats, bowlingStats: BowlingStats, imageUrl: string, bio: string): Promise<void>;
    updateRecord(id: bigint, category: RecordCategory, title: string, holder: string, value: string, year: bigint, format: MatchFormat): Promise<void>;
}
import type { BattingStats as _BattingStats, BowlingStats as _BowlingStats, Match as _Match, MatchFormat as _MatchFormat, MatchStatus as _MatchStatus, NewsArticle as _NewsArticle, NewsCategory as _NewsCategory, Player as _Player, PlayerRole as _PlayerRole, Record as _Record, RecordCategory as _RecordCategory, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createMatch(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: MatchFormat, arg5: MatchStatus, arg6: string, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg4), to_candid_MatchStatus_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg4), to_candid_MatchStatus_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
            return result;
        }
    }
    async createNewsArticle(arg0: string, arg1: string, arg2: NewsCategory, arg3: Time, arg4: string, arg5: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewsArticle(arg0, arg1, to_candid_NewsCategory_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewsArticle(arg0, arg1, to_candid_NewsCategory_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async createPlayer(arg0: string, arg1: string, arg2: PlayerRole, arg3: BattingStats, arg4: BowlingStats, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0, arg1, to_candid_PlayerRole_n7(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0, arg1, to_candid_PlayerRole_n7(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createRecord(arg0: RecordCategory, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: MatchFormat): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecord(to_candid_RecordCategory_n9(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecord(to_candid_RecordCategory_n9(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteMatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async deleteNewsArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsArticle(arg0);
            return result;
        }
    }
    async deletePlayer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async deleteRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsArticles(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsArticles();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsArticles();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecords(): Promise<Array<Record_>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecords();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecords();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: bigint): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_Match_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_Match_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsArticle(arg0: bigint): Promise<NewsArticle> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticle(arg0);
                return from_candid_NewsArticle_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticle(arg0);
            return from_candid_NewsArticle_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: bigint): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_Player_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_Player_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecord(arg0: bigint): Promise<Record_> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecord(arg0);
                return from_candid_Record_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecord(arg0);
            return from_candid_Record_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMatch(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: MatchFormat, arg6: MatchStatus, arg7: string, arg8: string, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(arg0, arg1, arg2, arg3, arg4, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg5), to_candid_MatchStatus_n3(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(arg0, arg1, arg2, arg3, arg4, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg5), to_candid_MatchStatus_n3(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
            return result;
        }
    }
    async updateNewsArticle(arg0: bigint, arg1: string, arg2: string, arg3: NewsCategory, arg4: Time, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsArticle(arg0, arg1, arg2, to_candid_NewsCategory_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsArticle(arg0, arg1, arg2, to_candid_NewsCategory_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async updatePlayer(arg0: bigint, arg1: string, arg2: string, arg3: PlayerRole, arg4: BattingStats, arg5: BowlingStats, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1, arg2, to_candid_PlayerRole_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1, arg2, to_candid_PlayerRole_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateRecord(arg0: bigint, arg1: RecordCategory, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: MatchFormat): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(arg0, to_candid_RecordCategory_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(arg0, to_candid_RecordCategory_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_MatchFormat_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_MatchFormat_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchFormat): MatchFormat {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_NewsArticle_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsArticle): NewsArticle {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_NewsCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsCategory): NewsCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerRole): PlayerRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_RecordCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordCategory): RecordCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record): Record_ {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    result: string;
    team1: string;
    team2: string;
    venue: string;
    date: _Time;
    score1: string;
    score2: string;
    format: _MatchFormat;
}): {
    id: bigint;
    status: MatchStatus;
    result: string;
    team1: string;
    team2: string;
    venue: string;
    date: Time;
    score1: string;
    score2: string;
    format: MatchFormat;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n14(_uploadFile, _downloadFile, value.status),
        result: value.result,
        team1: value.team1,
        team2: value.team2,
        venue: value.venue,
        date: value.date,
        score1: value.score1,
        score2: value.score2,
        format: from_candid_MatchFormat_n16(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    featured: boolean;
    date: _Time;
    summary: string;
    imageUrl: string;
    category: _NewsCategory;
}): {
    id: bigint;
    title: string;
    featured: boolean;
    date: Time;
    summary: string;
    imageUrl: string;
    category: NewsCategory;
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        date: value.date,
        summary: value.summary,
        imageUrl: value.imageUrl,
        category: from_candid_NewsCategory_n21(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    bowlingStats: _BowlingStats;
    country: string;
    name: string;
    role: _PlayerRole;
    battingStats: _BattingStats;
    imageUrl: string;
}): {
    id: bigint;
    bio: string;
    bowlingStats: BowlingStats;
    country: string;
    name: string;
    role: PlayerRole;
    battingStats: BattingStats;
    imageUrl: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        bowlingStats: value.bowlingStats,
        country: value.country,
        name: value.name,
        role: from_candid_PlayerRole_n26(_uploadFile, _downloadFile, value.role),
        battingStats: value.battingStats,
        imageUrl: value.imageUrl
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    value: string;
    year: bigint;
    category: _RecordCategory;
    holder: string;
    format: _MatchFormat;
}): {
    id: bigint;
    title: string;
    value: string;
    year: bigint;
    category: RecordCategory;
    holder: string;
    format: MatchFormat;
} {
    return {
        id: value.id,
        title: value.title,
        value: value.value,
        year: value.year,
        category: from_candid_RecordCategory_n31(_uploadFile, _downloadFile, value.category),
        holder: value.holder,
        format: from_candid_MatchFormat_n16(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
}): MatchStatus {
    return "upcoming" in value ? MatchStatus.upcoming : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ipl: null;
} | {
    odi: null;
} | {
    t20: null;
} | {
    test: null;
}): MatchFormat {
    return "ipl" in value ? MatchFormat.ipl : "odi" in value ? MatchFormat.odi : "t20" in value ? MatchFormat.t20 : "test" in value ? MatchFormat.test : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ipl: null;
} | {
    domestic: null;
} | {
    international: null;
}): NewsCategory {
    return "ipl" in value ? NewsCategory.ipl : "domestic" in value ? NewsCategory.domestic : "international" in value ? NewsCategory.international : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bowler: null;
} | {
    allrounder: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
}): PlayerRole {
    return "bowler" in value ? PlayerRole.bowler : "allrounder" in value ? PlayerRole.allrounder : "wicketkeeper" in value ? PlayerRole.wicketkeeper : "batsman" in value ? PlayerRole.batsman : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bowling: null;
} | {
    team: null;
} | {
    batting: null;
}): RecordCategory {
    return "bowling" in value ? RecordCategory.bowling : "team" in value ? RecordCategory.team : "batting" in value ? RecordCategory.batting : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsArticle>): Array<NewsArticle> {
    return value.map((x)=>from_candid_NewsArticle_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record>): Array<Record_> {
    return value.map((x)=>from_candid_Record_n29(_uploadFile, _downloadFile, x));
}
function to_candid_MatchFormat_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchFormat): _MatchFormat {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_MatchStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): _MatchStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NewsCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): _NewsCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): _PlayerRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_RecordCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordCategory): _RecordCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordCategory): {
    bowling: null;
} | {
    team: null;
} | {
    batting: null;
} {
    return value == RecordCategory.bowling ? {
        bowling: null
    } : value == RecordCategory.team ? {
        team: null
    } : value == RecordCategory.batting ? {
        batting: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchFormat): {
    ipl: null;
} | {
    odi: null;
} | {
    t20: null;
} | {
    test: null;
} {
    return value == MatchFormat.ipl ? {
        ipl: null
    } : value == MatchFormat.odi ? {
        odi: null
    } : value == MatchFormat.t20 ? {
        t20: null
    } : value == MatchFormat.test ? {
        test: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
} {
    return value == MatchStatus.upcoming ? {
        upcoming: null
    } : value == MatchStatus.live ? {
        live: null
    } : value == MatchStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): {
    ipl: null;
} | {
    domestic: null;
} | {
    international: null;
} {
    return value == NewsCategory.ipl ? {
        ipl: null
    } : value == NewsCategory.domestic ? {
        domestic: null
    } : value == NewsCategory.international ? {
        international: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): {
    bowler: null;
} | {
    allrounder: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
} {
    return value == PlayerRole.bowler ? {
        bowler: null
    } : value == PlayerRole.allrounder ? {
        allrounder: null
    } : value == PlayerRole.wicketkeeper ? {
        wicketkeeper: null
    } : value == PlayerRole.batsman ? {
        batsman: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
